name: coinconverterchallenge
description: A coin converter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  provider: ^4.3.3
  sembast: ^2.4.8+1
  get_it: ^5.0.6
  path_provider: ^1.6.27
  connectivity: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
